import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			className="min-w-full min-h-full text-white bg-zinc-800"
			lang="en">
			<body className={`${inter.className} min-h-screen min-w-full`}>
				{children}
			</body>
		</html>
	);
}
